/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge.vue')['default']
    Explanations: typeof import('./src/components/Explanations.vue')['default']
    FloatingImages: typeof import('./src/components/FloatingImages.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    IMaterialSymbolsArrowBackIosNewRounded: typeof import('~icons/material-symbols/arrow-back-ios-new-rounded')['default']
    IMaterialSymbolsArrowForwardIosRounded: typeof import('~icons/material-symbols/arrow-forward-ios-rounded')['default']
    IMaterialSymbolsBook2Rounded: typeof import('~icons/material-symbols/book2-rounded')['default']
    IMaterialSymbolsCircle: typeof import('~icons/material-symbols/circle')['default']
    IMaterialSymbolsCircleOutline: typeof import('~icons/material-symbols/circle-outline')['default']
    IMaterialSymbolsContactSupportRounded: typeof import('~icons/material-symbols/contact-support-rounded')['default']
    IMaterialSymbolsCrowdsource: typeof import('~icons/material-symbols/crowdsource')['default']
    IMaterialSymbolsHelpRounded: typeof import('~icons/material-symbols/help-rounded')['default']
    IMaterialSymbolsHistoryRounded: typeof import('~icons/material-symbols/history-rounded')['default']
    IMaterialSymbolsHomeRounded: typeof import('~icons/material-symbols/home-rounded')['default']
    IMaterialSymbolsMenuRounded: typeof import('~icons/material-symbols/menu-rounded')['default']
    IMaterialSymbolsSchoolRounded: typeof import('~icons/material-symbols/school-rounded')['default']
    IMaterialSymbolsSearchRounded: typeof import('~icons/material-symbols/search-rounded')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavPanel: typeof import('./src/components/NavPanel.vue')['default']
    PageContent: typeof import('./src/components/PageContent.vue')['default']
    Pagination: typeof import('./src/components/Pagination.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    RubyText: typeof import('./src/components/RubyText.vue')['default']
    SearchBar: typeof import('./src/components/SearchBar.vue')['default']
    SearchSkeleton: typeof import('./src/components/SearchSkeleton.vue')['default']
    SeeSymbol: typeof import('./src/components/SeeSymbol.vue')['default']
    SideBar: typeof import('./src/components/SideBar.vue')['default']
    Subtitle: typeof import('./src/components/Subtitle.vue')['default']
    WordCikLingCard: typeof import('./src/components/WordCikLingCard.vue')['default']
    WordCikLingEntry: typeof import('./src/components/WordCikLingEntry.vue')['default']
    WordFengCard: typeof import('./src/components/WordFengCard.vue')['default']
    WordPhoneticCard: typeof import('./src/components/WordPhoneticCard.vue')['default']
    WordsDeck: typeof import('./src/components/WordsDeck.vue')['default']
    WordSkeleton: typeof import('./src/components/WordSkeleton.vue')['default']
  }
}
